site_name: Dokumentation Projekt-1
dev_addr: '0.0.0.0:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png

site_author: "bszetdd it-systems"

extra_css:
    - css/extra.css
    
nav:
  - Home: index.md
  - Getting Started: user-guide/getting-started.md
  - Impressum: legal/imprint.md
  - Phase 1: Phase1/Phase1.md
  - Phase 2
  - Phase 3
  - Phase 4
  - Phase 5