site_name: Dokumentation Projekt-1
dev_addr: '0.0.0.0:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png

site_author: "bszetdd it-systems"

extra_css:
    - css/extra.css
    
nav:
  - Home: index.md
  - Anwendungsfalldiagramm: Anwendungsfalldiagramm.md
  - Vor-/Nachteile von Zielplattformen zur Softwareentwicklung: Zielplattformen.md 
  - Begriffserklärung: Begriffserklärung.md
  - Sequenzdiagramm: Sequenzdiagramm.md
  - Untersuchung der Datenformate bzw. Datenquellen: Datenformate.md
  - Impressum: legal/imprint.md